name: Validate PKGBUILD

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  updpkgsums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "package=$(git diff --name-only HEAD HEAD~1 "*/PKGBUILD" | head -1 | xargs dirname)" | tee -a "$GITHUB_OUTPUT"


      - name: Validate package
        if: ${{ steps.getPackage.outputs.package != '' }}
        uses: ./.github/actions/aur
        with:
          action: validate
          pkgname: ${{ steps.getPackage.outputs.package }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          git_email: ${{ secrets.AUR_EMAIL }}
          git_username: ${{ secrets.AUR_USERNAME }}
